# Generated by Django 6.0.8 on 2026-09-15 11:31

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.SlugField(max_length=64)),
                ('name', models.CharField(max_length=160)),
            ],
        ),
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.SlugField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.SlugField(max_length=100, unique=True)),
                ('state', models.CharField(choices=[('online', 'Online'), ('stale', 'Stale'), ('offline', 'Offline')], default='offline', max_length=12)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('cage', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='device', to='monitoring.cage')),
            ],
        ),
        migrations.AddField(
            model_name='cage',
            name='farm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cages', to='monitoring.farm'),
        ),
        migrations.CreateModel(
            name='FlockBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_id', models.SlugField(max_length=100, unique=True)),
                ('started_at', models.DateField()),
                ('bird_count', models.PositiveIntegerField()),
                ('initial_total_weight_kg', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('current_total_weight_kg', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('feed_consumed_kg', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('active', models.BooleanField(default=True)),
                ('cage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='monitoring.cage')),
            ],
        ),
        migrations.CreateModel(
            name='ThresholdConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature_low_c', models.FloatField(default=20)),
                ('temperature_high_c', models.FloatField(default=32)),
                ('humidity_low_rh', models.FloatField(default=40)),
                ('humidity_high_rh', models.FloatField(default=80)),
                ('ammonia_high_ppm', models.FloatField(default=25)),
                ('co2_high_ppm', models.FloatField(default=3000)),
                ('buzzer_hold_seconds', models.PositiveIntegerField(default=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cage', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='thresholds', to='monitoring.cage')),
            ],
        ),
        migrations.CreateModel(
            name='Tier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField()),
                ('name', models.CharField(blank=True, max_length=80)),
                ('cage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiers', to='monitoring.cage')),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='TelemetryReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sampled_at', models.DateTimeField()),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.CharField(choices=[('hardware', 'Hardware'), ('simulator', 'Simulator')], default='hardware', max_length=12)),
                ('temperature_c', models.FloatField(blank=True, null=True)),
                ('humidity_rh', models.FloatField(blank=True, null=True)),
                ('light_lux', models.FloatField(blank=True, null=True)),
                ('ammonia_ppm', models.FloatField(blank=True, null=True)),
                ('co2_ppm', models.FloatField(blank=True, null=True)),
                ('weight_kg', models.FloatField(blank=True, null=True)),
                ('actuators', models.JSONField(default=dict)),
                ('field_quality', models.JSONField(blank=True, default=dict)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('cage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telemetry', to='monitoring.cage')),
                ('tier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telemetry', to='monitoring.tier')),
            ],
            options={
                'ordering': ['-sampled_at'],
            },
        ),
        migrations.CreateModel(
            name='SecurityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detected_at', models.DateTimeField()),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.CharField(default='pir', max_length=20)),
                ('buzzer_activated', models.BooleanField(default=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('cage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='security_events', to='monitoring.cage')),
                ('tier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_events', to='monitoring.tier')),
            ],
            options={
                'ordering': ['-detected_at'],
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=80)),
                ('title', models.CharField(max_length=180)),
                ('detail', models.TextField(blank=True)),
                ('severity', models.CharField(choices=[('warning', 'Warning'), ('critical', 'Critical')], max_length=10)),
                ('opened_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('cage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='monitoring.cage')),
                ('tier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='monitoring.tier')),
            ],
            options={
                'ordering': ['-opened_at'],
            },
        ),
        migrations.CreateModel(
            name='ActuatorCommand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('target', models.CharField(max_length=30)),
                ('value', models.BooleanField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('published', 'Published'), ('executed', 'Executed'), ('rejected', 'Rejected'), ('failed', 'Failed')], default='pending', max_length=12)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledgement', models.JSONField(blank=True, default=dict)),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('cage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commands', to='monitoring.cage')),
                ('tier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commands', to='monitoring.tier')),
            ],
            options={
                'ordering': ['-requested_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='cage',
            constraint=models.UniqueConstraint(fields=('farm', 'external_id'), name='unique_cage_per_farm'),
        ),
        migrations.AddConstraint(
            model_name='tier',
            constraint=models.UniqueConstraint(fields=('cage', 'number'), name='unique_tier_per_cage'),
        ),
        migrations.AddIndex(
            model_name='telemetryreading',
            index=models.Index(fields=['cage', 'tier', '-sampled_at'], name='monitoring__cage_id_8b00fe_idx'),
        ),
    ]
